### ISSUE TITLE
请问你的项目用了TypeScript 编译器吗

### ISSUE THREAD

**Issue by cgq355716727** [easyfast/LawfirmOA#4]
错误	1	您的项目文件使用的 TypeScript 编译器和工具的版本不同于此机器上当前安装的版本。在 C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\tsc.exe 处未找到编译器。通过更改项目文件中的 <TypeScriptToolsVersion> 元素，或许可以修复此问题。

**Comment by easyfast** [comment]
还原包应该可以解决问题，项目没有使用ts。是升级包时自动添加的。

**Comment by easyfast** [comment]
补充：我用的VS2015.您可以升级ts包到1.8试试
