### ISSUE TITLE
ths for your  sharing,but be careful with your website information

### ISSUE THREAD

**Issue by ccccccmd** [easyfast/LawfirmOA#5]

**Comment by maliming** [comment]
@ccccccmd 
Have you found a website vulnerability?

**Comment by ccccccmd** [comment]
[web.config](https://github.com/easyfast/LawfirmOA/blob/master/EasyFast.Web/Web.config)

**Comment by maliming** [comment]
Thank you very much reminder. 😊
This is a public database, account without much Permissions, there is no important and secret of the data. Just for the show.
